// <auto-generated />
namespace NanatsuNoTaizai.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateCharactersColumnInDT_Abilities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateCharactersColumnInDT_Abilities));
        
        string IMigrationMetadata.Id
        {
            get { return "202110300925136_CreateCharactersColumnInDT_Abilities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
